### ISSUE TITLE
Repository 'http://deb.debian.org/debian buster InRelease' changed its 'Suite' value from 'stable' to 'oldstable'

### ISSUE THREAD

**Issue by matthieudesprez** [CircleCI-Public/aws-elastic-beanstalk-orb#15]
## Orb version:

1.0.0 but also tested with 2.0.0 

```yaml
build_executor:
    docker:
      - image: circleci/python:3.8.1-buster-node-browsers
```
## What happened:

Failure during "Setting Up Elastic Beanstalk CLI"
```
E: Repository 'http://deb.debian.org/debian buster InRelease' changed its 'Suite' value from 'stable' to 'oldstable'
E: Repository 'http://deb.debian.org/debian buster-updates InRelease' changed its 'Suite' value from 'stable-updates' to 'oldstable-updates'
E: Repository 'http://security.debian.org/debian-security buster/updates InRelease' changed its 'Suite' value from 'stable' to 'oldstable
```

## Expected behavior:

On August, 12 2021 everything was still working fine using the 1.0.0
