### ISSUE TITLE
Trying to deploy ELB

### ISSUE THREAD

**Issue by hrufna** [CircleCI-Public/aws-elastic-beanstalk-orb#5]
## Orb version: 1.0.0

Hi, I am trying to use the elastic-beanstalk orb to automate the deployment process of a Java application I am currently hosting on AWS Elastic Beanstalk, and I am getting an ERROR: InvalidParameterValueError - No Application Version named 'kanban-server-19' found. On my AWS ELB Application versions page, I do not see any 'kanban-server-19" being generated, and yet I do see 'kanban-server-19.zip' stored in my s3.

I am using the following config.yml:

version: 2.1

orbs:
  maven: circleci/maven@0.0.12
  eb: circleci/aws-elastic-beanstalk@1.0.0

workflows:
  maven_test:
    jobs:
      - maven/test # checkout, build, test, and upload test results
      - eb/deploy:
        context: aws
        environment-name: TrulyKanbanServer-env
        filters:
          branches:
            only:
              - master
        label: kanban-server-<<pipeline.number>>
        requires:
              - maven/test

The log output i get is:

#!/bin/bash -eo pipefail
eb init TrulyKanbanServer-env -r $AWS_DEFAULT_REGION -p node.js
eb deploy TrulyKanbanServer-env -l kanban-server-19 

Application TrulyKanbanServer-env has been created.
Creating application version archive "kanban-server-19".
Uploading TrulyKanbanServer-env/kanban-server-19.zip to S3. This may take a while.
Upload Complete.
ERROR: InvalidParameterValueError - No Application Version named 'kanban-server-19' found.

Exited with code exit status 4
CircleCI received exit code 4

**Comment by doublelobster-devops** [comment]
Same issue here, really not sure what's happening, did you get anywhere with this?

**Comment by nathan-appere** [comment]
Same issue here, really not sure what's happening, did you get anywhere with this?

**Comment by nathan-appere** [comment]
Found it: the call to `eb init` is invalid, it should be the application name and not the environment name. I bypassed the orb.

**Comment by map-lo** [comment]
+1

**Comment by tniezurawski** [comment]
I had the same problem. I was following the docs and thanks to @nathan-appere's answer I realized I have to specify `application-name` as well:

```diff
version: '2.1'
orbs:
  eb: circleci/aws-elastic-beanstalk@1.0.0
  node: circleci/node@4.1.0
workflows:
  elastic-beanstalk-workflow:
    jobs:
      - node/test
      - eb/deploy:
          context: aws-creds
+         application-name: my-app-name
+         environment-name: my-app-environment-name
-         environment-name: my-app
          filters:
            branches:
              only:
                - main
          label: version-<<pipeline.number>>
          requires:
            - node/test
```

I'm not sure if `environment-name` is needed or not 🤷‍♂️ but the above works for me.

----

@KyleTryon Should I raise a PR with a change for https://github.com/CircleCI-Public/aws-elastic-beanstalk-orb/blob/5887cb15c4e6ae36f67a361e7fcec5e72d397b28/src/examples/deploy_eb_application_to_env.yml#L15-L17 ?

How do you folks update this one? https://circleci.com/developer/orbs/orb/circleci/aws-elastic-beanstalk
Unless that was a coincidence that my deployment started to work after adding `application-name` 😅

**Comment by michaelbrant** [comment]
I'm getting this error after adding application name:
`Unexpected argument(s): application-name`

**Comment by michaelbrant** [comment]
> I'm getting this error after adding application name:
> `Unexpected argument(s): application-name`

Changing the orb fixed this


```
version: 2.1
orbs:
  aws-elastic-beanstalk: circleci/aws-elastic-beanstalk@2.0.1
workflows:
  elastic-beanstalk-workflow:
    jobs:
      - aws-elastic-beanstalk/deploy:
          context: nxtCRE Context
          environment-name: prod-env
          application-name: prod-app
          filters:
            branches:
              only:
                - prod
```

**Comment by tniezurawski** [comment]
@michaelbrant You are right. I was "fixing" what's in docs but in fact, I do also use a newer orb (1 patch version behind you):

```yml
orbs:
  node: circleci/node@4.1
  eb: circleci/aws-elastic-beanstalk@2.0.0

# [...] Some other things like jobs

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build-and-test
      - eb/deploy:
          context: aws-creds
          application-name: my-app-name
          environment-name: my-app-environment-name
          filters:
            branches:
              only:
                - master
          label: my-app-name-source-<<pipeline.number>>
          requires:
            - build-and-test
```

I wasn't aware it's not going to work with `@1.0.0` 😅 Sorry!
